version: '3.9'

services:
  mongo_db:
    container_name: mongodb_container
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    
  api_service:
    container_name: messanger_api_container
    build: ./messanger-api/
    ports:
      - "7777:7777" 
    environment:
      - PORT=7777
      - MONGODB_URI=mongodb://mongo_db:27017/messanger_app
    depends_on:
      - mongo_db

  socket_service:
    container_name: messanger_socket_container
    build: ./messanger-socket-server/
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - MONGODB_URI=mongodb://mongo_db:27017/messanger_app
    depends_on:
      - mongo_db

volumes:
  mongodb_data:
    external: true